webdriver {
	driver = chrome
	autodownload = true
	capabilities {
		browserName = "chrome"
		"goog:chromeOptions" {
			args = ["--start-maximized", "--disable-popup-blocking", "--remote-allow-origins=*", "--no-sandbox", "--disable-dev-shm-usage"]
			prefs {
				download.prompt_for_download = false
			}
		}
	}
}

serenity {
	browser.maximized = true
	take.screenshots = FOR_FAILURES
	project.name = "AUTO_FRONT_SCREENPLAY - SistemaTickets UI Tests"
}

environments {
	default {
		webdriver.base.url = "http://localhost:5173"
	}
}

headless.mode = ${?HEADLESS_MODE}
